baseURL = "/"
languageCode = "es-es"
title = "Entre La Razón Y La Fe"
theme = "hugo-PaperMod" #tema

[pagination]
  pagerSize = 15

[params]
  description = "Blog de Jorge Ayona"
  highlightColor = "#e22d30"
  mainSections = ["posts"]

# Configuración del Favicon (Mantenemos lo que ya funciona)
[params.assets]
    favicon = "/favicon.ico"
    favicon16x16 = "/favicon.ico"
    favicon32x32 = "/favicon.ico"
    apple_touch_icon = "/favicon.ico"

# --- NUEVA SECCIÓN: IMAGEN DE CABECERA (BANNER) ---
[params.profileMode]
    enabled = true
    title = "Entre La Razón Y La Fe"
    subtitle = "Blog de Jorge Ayona"
    imageUrl = "/cabecera.jpg" # Tu imagen de la carpeta static
    imageWidth = 1000          # Ancho para que se vea como banner
    imageHeight = 300          # Ajusta la altura a tu gusto
# --------------------------------------------------

[params.cover]
      linkFullImages = true
      responsiveImages = false
      hidden = false
      hiddenInList = false
      hiddenInSingle = false

[params.sidebar]
  home = "right"
  widgets = ["search", "recent", "categories"]

[params.thumbnail]
  visibility = ["list", "post"]

[markup.goldmark.renderer]
  unsafe = true
